spring.datasource.url=jdbc:postgresql://localhost:5434/quietcorner
spring.datasource.username=postgres
spring.datasource.password=madik

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=dGhpcyBpcyBhIHZlcnkgc3VwZXIgZGVsaWNhdGUgc2VjcmV0IGtleSBmb3Igand0IHRlc3Rpbmc=
jwt.expiration=86400000
